### ISSUE TITLE
WARNING:root:Could not load CuPy: No module named 'cupy'

### ISSUE THREAD

**Issue by RobbeRamon** [Skielex/structure-tensor#10]
I am calling the structure_tensor_2d function but I do get the error that cupy is not found. I thought this was only necessary for 3D? Do you know what the solution is? I am working on a mac computer so no nvidia graphics card is available.

**Comment by RobbeRamon** [comment]
Seems to be only a warning so I guess I can just ignore this

**Comment by Skielex** [comment]
Yeah, you can safely ignore that warning. I probably shouldn't have chosen to import `parallel_structure_tensor_analysis` in the init file.
