### ISSUE TITLE
package cupyx.scipy.ndimage.filters deprecated 

### ISSUE THREAD

**Issue by choROPeNt** [Skielex/structure-tensor#14]
Hello I just ran in the following error when I wanted to test my installation with `tests/test_strucutre_tensor.py`:

```
DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
```

```
WARNING:root:Could not load CuPy: cannot import name 'filters' from 'cupyx.scipy.ndimage'
```

found a description of the problem in the [IMAGE.sc forum](https://forum.image.sc/t/new-median-filter-commands/63918)

## Build

- Python==3.10
- CUDA==11.8
- cupy-cuda11x==12.3.0
- scipy==1.11.4

## Solution

change in `./structure-tensor/cp/st3dcp.py` line 6 and `.structure-tensor/st3d.py` line 5
```python
from cupyx.scipy.ndimage import filters
```
to 
```python
import cupyx.scipy.ndimage as filters
```
as a workaround.

Hope this could help anyone who encounters the same problem

**Comment by Skielex** [comment]
Thanks for raising the issue. I'll fix the import and make a new release.

**Comment by choROPeNt** [comment]
small mistake in my solution. In 'st3d.py' you have to replace 

```python
from scipy.ndimage import filters
```
to

```python
import scipy.ndimage as filters
```

Test works smoothly now:
```
..........
----------------------------------------------------------------------
Ran 10 tests in 2.268s

OK
```
