### ISSUE TITLE
Bug in `parallel_structure_tensor_analysis` when `include_all_eigenvalues=True`

### ISSUE THREAD

**Issue by patmjen** [Skielex/structure-tensor#16]
## Description and example

Calling `parallel_structure_tensor_analysis` with `include_all_eigenvalues=True` results in an exception. 
The following example reproduces the error on my system:
```
import numpy as np
import structure_tensor as st

x = np.zeros((50, 50, 50))
st.parallel_structure_tensor_analysis(
    x,
    1.0, 1.0,
    block_size=30,
    include_all_eigenvalues=True,
)
```

## Reason and possible fix
I think the issue lies in [multiprocessing.py](https://github.com/Skielex/structure-tensor/blob/6fe5ba4322951a40fbfe2e85d90e0e593a433c6a/structure_tensor/multiprocessing.py) when `eigenvectors_shape` and `eigenvalues_shape` are defined (L110 and L146). It should maybe have been switched, so the eigenvector array is (3, 3, volume.shape) when `include_all_eigenvalues=True` and the eigenvalue array is always (3, volume.shape). This at least removes the exception, although I have not verified the output *values* yet.

**Suggestion:** if the `include_all_eigenvalues` parameter actually refers to whether to include all the eigen**vectors**, then it should maybe be renamed to `include_all_eigenvectors` (unless I'm missing something).

**Comment by Skielex** [comment]
Hmm, yeah, looks like I messed that up pretty good. I'll have a look at it when I'm back from vacation. 
Thanks for reporting!

**Comment by Skielex** [comment]
Hopefully this solves the issues.

**Comment by Skielex** [comment]
Note: I changed this return value, so that it's always a tuple with three values.

`S, val, vec = parallel_structure_tensor_analysis(data, sigma, rho, devices=4*['cuda'], block_size=200)`
