### ISSUE TITLE
Question on the sorting order of the returned eigenvalues

### ISSUE THREAD

**Issue by ckolluru** [Skielex/structure-tensor#8]
Hi,

It is mentioned in the readme that the eigenvalues returned are provided in ascending order. When referring to [this ](https://dl.acm.org/doi/pdf/10.1145/355578.366316) paper, the eigenvalues for a symmetric 3x3 matrix are:

$m + 2 \sqrt{p} cos (\phi)$
$m - \sqrt{p} (cos (\phi) + \sqrt(3) sin(\phi))$
$m - \sqrt{p} (cos (\phi) - \sqrt(3) sin(\phi))$

When these values are plotted for $\phi$ running from 0 to 180 $\textdegree$, I get the following plot. Note that m and p are arbitrarily chosen numbers in this case, but I see a similar pattern for other choices as well.

![image](https://user-images.githubusercontent.com/8373968/184463639-08635058-622d-42d7-8106-ef46ee30c9a5.png)

From this plot, it looks like the smallest eigenvalue depends on the angle $\phi$. In the [code](https://github.com/Skielex/structure-tensor/blob/master/structure_tensor/st3d.py#L216), the smallest eigenvalue (and thus the corresponding eigenvector) are set to $m - \sqrt{p} (cos (\phi) + \sqrt(3) sin(\phi))$, but this is not the case for all $\phi$.

Let me know what you think.

Thanks,
Chaitanya

**Comment by Skielex** [comment]
Hi Chaitanya,

Good question. I'll check with my co-author as she did the implementation, which mine is based on. From my testing, the returned eigenvalues should the sorted correctly, i.e., `val[0] <= val[1] <= val[2]`. Have you experienced situations where this wasn't the case?

Best,
Niels

**Comment by ckolluru** [comment]
Thanks for your response. You're right, I just checked and the values are always in ascending order for my dataset. 

In the paper, from the definition of $\phi$

![image](https://user-images.githubusercontent.com/8373968/184579643-07400a45-83de-4cbc-a32c-deb14cdc9b02.png)

The factor of 1/3 results in $\phi$ to be under 60 $\degree$. From the graph shown, we find that black < red < blue for angles between 0 and 60 $\degree$. Hence val[0] <= val[1] <= val[2].

Thanks,
Chaitanya

Update: In an earlier version of this comment, I mentioned that numpy.linalg.eig seemed faster than this method. I was incorrect, this version is faster. Sorry about that.

**Comment by ckolluru** [comment]
Just one more thing before I close this issue, do you see any large differences between the eigenvalues calculated with this method and those returned by numpy.linalg.eig? When I check this, a large percentage have minute differences, but there are a few large outliers which I wasn't expecting. Have you tried checking this at your end?

**Comment by Skielex** [comment]
Glad you found the answer!
Tbh I haven't benchmarked the code against other algorithms, only against the MATLAB code which it's based on. So please let me know if you run into any issues.

Best,
Niels
